import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { cn } from '@/lib/utils'

import './globals.css'

import { ReactNode } from 'react'

const fontDisplay = localFont({
  src: [
    // {
    //   weight: '100',
    //   path: './fonts/objectSans/PPObjectSans-Thin.woff2',
    //   style: 'normal',
    // },
    // {
    //   weight: '100',
    //   path: './fonts/objectSans/PPObjectSans-ThinSlanted.woff2',
    //   style: 'italic',
    // },
    // {
    //   weight: '300',
    //   path: './fonts/objectSans/PPObjectSans-Regular.woff2',
    //   style: 'normal',
    // },
    // {
    //   weight: '300',
    //   path: './fonts/objectSans/PPObjectSans-Slanted.woff2',
    //   style: 'italic',
    // },
    {
      weight: '600',
      path: './fonts/objectSans/PPObjectSans-Bold.woff2',
      style: 'normal',
    },
    // {
    //   weight: '600',
    //   path: './fonts/objectSans/PPObjectSans-BoldSlanted.woff2',
    //   style: 'italic',
    // },
    {
      weight: '800',
      path: './fonts/objectSans/PPObjectSans-Heavy.woff2',
      style: 'normal',
    },
    {
      weight: '800',
      path: './fonts/objectSans/PPObjectSans-HeavySlanted.woff2',
      style: 'italic',
    },
  ],
  display: 'swap',
  variable: '--font-display',
})

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable)}>
        {children}
      </body>
    </html>
  )
}
